package com.sh.course.controller.command.parameter;

public enum CommandName {
	SIGN_IN_PAGE,
	REGISTRATION_PAGE,
	SIGN_IN,
	SIGN_OUT,
	PROFILE_PAGE,
	CHECK_IN,
	
	PASSWORD_RECOVERY,
	PASSWORD_RECOVERY_PAGE,
	
	ADD_COURSE_PAGE,
	ADD_COURSE,
	
	GET_AVAILABLE_COURSE,
}
