package com.sh.course.controller.command.parameter;

public enum CommandName {
	SIGN_IN_PAGE,
	REGISTRATION_PAGE,
	SIGN_IN,
	SIGN_OUT,
	PROFILE_PAGE,
	CHECK_IN,
	
	PASSWORD_RECOVERY,
	PASSWORD_RECOVERY_PAGE,
	
	ADD_COURSE_PAGE,
	ADD_COURSE,
	GOOD_ADD_COURSE,
	BED_ADD_COURSE,
	BED_ADD_HAS_TITLE_COURSE,
	BED_ADD_INVALID_COURSE,
	
	SEARCH_AVAILABLE_COURSE,
	GET_AVAILABLE_COURSE,
	GET_ALL_COURSE_LECTURER,
	
	ADD_LECTURER_COURSE,
	DELETE_LECTURER_COURSE,
	
	GOOD_ADD_LECTURER_COURSE,
	BED_ADD_LECTURER_COURSE,
	GOOD_DELETE_LECTURER_COURSE,
	BED_DELETE_LECTURER_COURSE,

	GET_ALL_LECTURER_COURSE,
	
	ENROLL_FOR_COURSE,
	GOOD_ENROLL_FOR_COURSE,
	BED_ENROLL_FOR_COURSE,
	BED_ENROLL_FOR_COURSE_HAS,
	
	GET_STUDENT_STUDY,
	GET_STUDENT_FINISH,
	
	RATE_STUDENT_PAGE,
	RATE_STUDENT,
}
